import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface QuotationData {
  quotation_number: string;
  date: string;
  valid_until: string;
  from_company: string;
  from_email: string;
  to_company: string;
  to_email: string;
  product: string;
  quantity: string;
  unit_price: string;
  incoterm: string;
  lead_time: string;
  payment_terms: string;
  destination: string;
  notes: string;
}

export function generateQuotationPDF(data: QuotationData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("QUOTATION", 14, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`No: ${data.quotation_number}`, pageWidth - 14, 12, { align: "right" });
  doc.text(`Date: ${data.date}`, pageWidth - 14, 20, { align: "right" });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 40);
  doc.text("TO", pageWidth / 2, 40);
  doc.setFont("helvetica", "normal");
  doc.text(data.from_company, 14, 47);
  doc.text(data.from_email, 14, 53);
  doc.text(data.to_company, pageWidth / 2, 47);
  doc.text(data.to_email, pageWidth / 2, 53);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, 60, pageWidth - 14, 60);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("PRODUCT DETAILS", 14, 70);

  autoTable(doc, {
    startY: 75,
    head: [["Field", "Details"]],
    body: [
      ["Product", data.product],
      ["Quantity", data.quantity],
      ["Unit Price", data.unit_price],
      ["Incoterm", data.incoterm],
      ["Destination", data.destination],
      ["Lead Time", data.lead_time],
      ["Payment Terms", data.payment_terms],
      ["Quotation Validity", `Valid until ${data.valid_until}`],
    ],
    headStyles: { fillColor: [15, 118, 110] },
    alternateRowStyles: { fillColor: [245, 250, 250] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 55 },
    },
  });

  const tableDocument = doc as jsPDF & { lastAutoTable?: { finalY: number } };
  const finalY = (tableDocument.lastAutoTable?.finalY ?? 75) + 10;

  if (data.notes) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("NOTES", 14, finalY);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const splitNotes = doc.splitTextToSize(data.notes, pageWidth - 28);
    doc.text(splitNotes, 14, finalY + 7);
  }

  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, footerY - 5, pageWidth - 14, footerY - 5);
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("All prices are indicative and subject to final confirmation. This is not a legally binding document.", 14, footerY);
  doc.text("Generated by Import Export AI Assistant", pageWidth - 14, footerY, { align: "right" });

  doc.save(`Quotation_${data.quotation_number}.pdf`);
}
